Aparna hcl dev
hariharan-devarajan/hcl pull request #1
Opened 2022-12-20 14:32 UTC by aparnasasidharan2017

I have added three data structures to HCL. Do you want to merge them with develop?

2023-02-17 19:02 UTC, hariharan-devarajan commented
@aparnasasidharan2017 does these work with dynamic values as containers such as https://github.com/hariharan-devarajan/hcl/blob/dev/test/unordered_map_string_test.cpp#L121 I use dynamic strings?

2023-02-17 21:45 UTC, hariharan-devarajan commented
@aparnasasidharan2017 Also squash all the commits into one. https://www.internalpointers.com/post/squash-commits-into-one-git

2023-02-17 21:45 UTC, hariharan-devarajan requested changes
I have left some comments to improve the tests and squashing all commits into 1.

2023-02-20 16:38 UTC, aparnasasidharan2017 commented
@hariharan-devarajan I have modified the testcases to cover shared-memory throughput and rpc throughput. My implementations do not use boost interprocess memory mapping for on-node rpc calls. I have assumed the implementation would use libfabric + shm instead of sockets for on-node communication. So, there are two code sections in the test cases : local function calls on servers and rpc calls from clients to servers.

2023-02-20 18:39 UTC, hariharan-devarajan commented
> @hariharan-devarajan I have modified the testcases to cover shared-memory throughput and rpc throughput. My implementations do not use boost interprocess memory mapping for on-node rpc calls. I have assumed the implementation would use libfabric + shm instead of sockets for on-node communication. So, there are two code sections in the test cases : local function calls on servers and rpc calls from clients to servers.

the boost interprocess is only used to do node-local shared memory calls on the shared memory created by the servers. So in my tests, I have the following three blocks.

1. a local data structure (std implementations) as baseline to understand performance of your distributed data structure.
2. performance of your data structure on shared memory created by the server on that node. For this, you can hash the requests to the node-local servers so that they do not do RPC calls but do update directly on shared memory.
3. performance of your data structure across nodes, which uses rpc to communicate to the server and then uses shm calls to update the shared memory region on that node.

Whether you use direct shm or boost interprocess, all three cases would apply.

2023-02-20 18:56 UTC, hariharan-devarajan commented
@aparnasasidharan2017 Please address the API concern I have Then i will merge the PR

2023-02-20 19:11 UTC, aparnasasidharan2017 commented
@hariharan-devarajan My testcases have 2 & 3 (shm and RPC). I didn't add a  baseline stl implementation because it will have to be single threaded or under a coarse lock. I'll add stl+coarse locks as baseline.

2023-03-10 09:09 UTC, hariharan-devarajan requested changes

2023-03-10 14:44 UTC, aparnasasidharan2017 commented on test/skiplist_test.cpp
> +        uint64_t k = s->serverLocation(value);
I have made the changes. It makes sense for hashtables and skiplist.

2023-03-10 17:59 UTC, hariharan-devarajan commented
@aparnasasidharan2017 Thank you for your patience with the PR. It looks good now.

2023-03-10 18:00 UTC, merged